config/routes.rb
Mycode::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  resources :users

  resources :snippets do
    member do
      get 'download'
    end
  end
  resources :categories,:only => [:show]
  mount Resque::Server, :at => "/resque"

  root :to => 'snippets#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :short_name
  has_many :snippets, :foreign_key => "language"
end

app/models/snippet.rb
#encoding: utf-8
class Snippet < ActiveRecord::Base
  attr_accessible :highlighted_code, :language, :name, :source_code, :description
  belongs_to :category,:foreign_key => 'language', :counter_cache => true
  belongs_to :user,:counter_cache => true

  default_scope :order => 'created_at DESC'

  validates :name, :length => { maximum: 20 , message: "最长为20个字符" },
    :presence => { message: "name 不能为空" }
  validates :source_code, :presence => { message: "不能为空" }


  @queue = :snippet_queue

  def self.perform(id)
  	snippet = Snippet.find_by_id(id)
    uri = URI.parse('http://pygments.simplabs.com/')
    request = Net::HTTP.post_form(uri,{ 'lang' => snippet.category.short_name, 'code' => snippet.source_code })
    snippet.update_attribute(:highlighted_code, request.body)
  end

  def lan_name
  	self.category.try(:name)
  end

  def author
    self.user.try(:email) || "admin"
  end

  def is_own?
      User.current && User.current.id == self.user_id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :snippets

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_current_user
  protect_from_forgery

  def login_required
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  protected

  def set_current_user
      User.current = current_user
  end
end

app/controllers/categories_controller.rb
#encoding: utf-8
class CategoriesController < ApplicationController
  def show
    @category = Category.includes(:snippets).find(params[:id])
    @snippets = @category.snippets
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category}
    end
  end
end

app/controllers/snippets_controller.rb
#encoding: utf-8
require 'net/http'
require 'uri'

class SnippetsController < ApplicationController
  
  before_filter :login_required,:except => [:index,:show]
  
  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = if !params[:key].blank?
      Snippet.where("name like ? ","%#{params[:key]}%")
    else
      Snippet.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snippets }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.json
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/1/edit
  def edit
    @snippet = Snippet.find(params[:id])
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(params[:snippet])
    @snippet.user_id = current_user.id 
    respond_to do |format|
      if @snippet.save
        # Resque.enqueue(Snippet, @snippet.id) # heroku redis not free
        # resque_job(@snippet)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render json: @snippet, status: :created, location: @snippet }
      else
        format.html { render action: "new" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snippets/1
  # PUT /snippets/1.json
  def update
    @snippet = Snippet.find(params[:id])
    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        #Resque.enqueue(Snippet, @snippet.id)  # heroku redis not free
        #resque_job(@snippet)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end

  def download 
    @snippet = Snippet.find(params[:id])
    @content = @snippet.source_code # get the content 
    file_name = "#{@snippet.name}.txt" 
    send_data @content,  
    :type => 'text',   
    :disposition => "attachment; filename=#{file_name}"
  end

  protected

  def resque_job(snippet)
    uri = URI.parse('http://pygments.simplabs.com/')
    request = Net::HTTP.post_form(uri,{ 'lang' => snippet.category.short_name, 'code' => snippet.source_code })
    snippet.update_attribute(:highlighted_code, request.body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @snippets = @user.snippets
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def language_list
		Category.where("snippets_count > ?",0)
	end
end

app/helpers/snippets_helper.rb
module SnippetsHelper

	def languages
		Category.all.collect {|c| [c.name,c.id]}
	end
end

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= @category.name %></b> 分类下的代码
</p>

<% @snippets.each do |s| %>
<p>
  
  <h3><%=link_to s.name, s %></h3>
</p>
<p>
  <b>Author:</b>
  <%= s.author %>
</p>
<p>
  <b>Language:</b>
  <%= s.lan_name %>
</p>

<p>
  <b>Description</b>
  <%=s.description%>
</p>

<p>
  <% if s.highlighted_code.present? %>
    <%=raw s.highlighted_code %>
  <%else%>
    <pre><%= s.source_code %></pre>
  <% end %>
</p>

<% end %>

<%= link_to 'Back', snippets_path %>

app/views/layouts/_footer.html.erb
<p><%=link_to "Socode","https://github.com/pobing/socode"%> Copyright © 2013 By <%=link_to "pobing","https://github.com/pobing"%></p>

app/views/layouts/_siderbar.html.erb
<h3>Language Lists</h3>
<ul>
  <%  language_list.each do |l| %>
    <li><%= link_to l.name, l %> [<%= l.snippets_count %>] </li>
  <% end %>
</ul>

app/views/layouts/_top.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">SoCode</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <!--               <li class="active"><a href="#">m1</a></li>
                        <li class="dropdown">
                          <a href="m2" class="dropdown-toggle" data-toggle="dropdown"> m5 <b class="caret"></b></a>
                          <ul class="dropdown-menu">
                            <li><a href="#">m3</a></li>
                            <li><a href="#">m4</a></li>
                          </ul>
                        </li>
          -->
          <% if user_signed_in? %>
            <li><%= link_to "<i class='icon-file'> 添加代码</i>".html_safe, new_snippet_path %></li>
          <%  end %>
        </ul>

        <%= form_tag snippets_path, :method => 'get', :class=>"navbar-search pull-left"  do %>
          <p>
            <%= text_field_tag :key, params[:key], :class=> "search-query span2",:placeholder=>"Search" %>
          </p>
        <% end %>

        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li> <%=link_to current_user.email,"#" %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">帐号 <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%#=link_to "houtaiguanli","#"%></li>
                <li><%= link_to "安全退出", destroy_user_session_path,:method =>:delete %></li>
              </ul>
            </li>
          <% else %>
            <li> <%= link_to "注册", new_user_registration_path %> </li>
            <li> <%= link_to "登录", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SoCode" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

 <!-- <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css"> -->
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%=render "layouts/top"%>

    <div class="container">
        <div class="row">
          <div class="span8">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <% if language_list.length > 0 %>
                <%=render "layouts/siderbar" %>
              <%  end %>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->
<hr>
      <footer>
        <%=render "layouts/footer"%>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "代码名称" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "选择语言类别" %><br />
    <%= f.select :language, languages, { :include_blank => true } %>
  </div>
    <div class="field">
    <%= f.label "你的代码" %><br />
    <%= f.text_area :source_code ,:class =>"code_text", :placeholder=>"复制您的代码到此..." %>
  </div>
  <div class="field">
    <%= f.label "描述" %><br />
    <%= f.text_area :description ,:class =>"desc_area",:placeholder => "为您的代码添加描述" %>
  </div>


  <div class="actions">
    <%= f.submit "添加",:class=>"btn" %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h2>编辑代码</h2>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to '返回', snippets_path %>

app/views/snippets/index.html.erb
<div class="span8">
  <% @snippets.each do |snippet| %>
    <h4><%=link_to snippet.name,snippet %></h4>
    <p>语言类别：<%=link_to snippet.lan_name,snippet.category %> &nbsp;&nbsp;<%= link_to snippet.author, snippet.user %> </p>
    <p><%= snippet.description %> </p>
    <p>
      <%= snippet.created_at.strftime("%Y-%m-%-d %H:%M:%S") %>&nbsp;&nbsp;
      <%=link_to "<i class='icon-star'></i>".html_safe, "#",:title =>"收藏" %>
      <%  if snippet.is_own? %>
        <%= link_to '编辑', edit_snippet_path(snippet) %>
        <%= link_to '删除', snippet, method: :delete, data: { confirm: '确定删除?' } %>
      <%  end %>
    </p>
    <p><%=link_to "查看详情 »",snippet,:class => "btn" %>
    <% end %>
</div>

app/views/snippets/new.html.erb
<div class="span8">
  <h2>添加新代码</h2>

  <%= render 'form' %>

  <%= link_to '返回', snippets_path %>

</div>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>标题:</b>
  <%= @snippet.name %>
</p>

<p>
  <b>语言类别:</b>
  <%= @snippet.lan_name %>
</p>

<p>
  <b>代码描述</b>
  <%=@snippet.description%>
</p>

<p>
  <b>源码:</b>
  <% if @snippet.highlighted_code.present? %>
    <%=raw @snippet.highlighted_code %>
  <%else%>
  <pre><%= @snippet.source_code %></pre>
<% end %>
</p>
<%= link_to '下载源码',download_snippet_path(@snippet) %>
<%  if @snippet.is_own?  %>
  <%= link_to '编辑', edit_snippet_path(@snippet) %>
  <%= link_to '删除', @snippet, method: :delete, data: { confirm: '确定删除?' } %>
<%  end %>
<%= link_to '返回', snippets_path %>

app/views/users/show.html.erb
<div class="span8">
<b><%=@user.email%></b> 共发布 <%=@user.snippets_count %> 篇代码
  <% @snippets.each do |snippet| %>
    <h2><%=link_to snippet.name,snippet %></h2>
    <p>语言类别：<%=link_to snippet.lan_name,snippet.category %> &nbsp;&nbsp;<%= link_to snippet.author, snippet.user %> </p>
    <p><%= snippet.description %> </p>
    <p>
      <%= snippet.created_at.strftime("%Y-%m-%-d %H:%M:%S") %>
      <%  if snippet.is_own? %>
        <%= link_to '编辑', edit_snippet_path(snippet) %>
        <%= link_to '删除', snippet, method: :delete, data: { confirm: '确定删除?' } %>
      <%  end %>
    </p>
    <p><%=link_to "查看详情 »",snippet,:class => "btn" %>
    <% end %>
</div>